version: '3.7'

services:
  opa-server:
    image: openpolicyagent/opa:0.24.0-envoy
    container_name: opa-server
    hostname: opa-server
    restart: unless-stopped
    networks:
      - proxy-net
    command:
      - "run"
      - "--server"
      - "--set=decision_logs.console=true"
      - "--log-format=json-pretty"
      - "--log-level=debug"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      - "/config/policy.rego"
    ports:
      - 8181:8181
    volumes:
      - ./policy/req_authz.rego:/config/policy.rego

networks:
  proxy-net:
    external:
      name: tempfiledrop_bridge
