version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    # hostname: dev-rmq01
    # networks:
    #   - rabbit-mq-network
    network_mode: host
    ports:
      - 15672:15672 # management port
      - 5672:5672 # connection port
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "15672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_ERLANG_COOKIE: 'cluster_cookie'
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
    volumes:
      - ./storage/rabbitmq-node-1:/var/lib/rabbitmq

#networks
# rabbitmq-network:
#   driver: bridge