version: '3.7'

# starts 2 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access it through port 9000.
services:
  minio1:
    hostname: minio1
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    container_name: 'minio_server_1'
    networks:
      - proxy-net
    volumes:
      - ./storage/data1-1:/data1
      - ./storage/data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    hostname: minio2
    container_name: 'minio_server_2'
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    networks:
      - proxy-net
    volumes:
      - ./storage/data2-1:/data1
      - ./storage/data2-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-nginx:
    hostname: minio-nginx
    container_name: 'minio_gateway'
    image: nginx:1.19.2-alpine
    networks:
      - proxy-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2

networks:
  proxy-net:
    external:
      name: tempfiledrop_bridge