###############################################################################################
# Server Configuration
###############################################################################################

server.port: 9090

spring:
  profiles.active: dev
  application.name: apigateway

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG

gateway:
  jwt-keycloak-parser:
    resource: storage-gateway           # Client
    use-resource-role-mappings: true    # use client role
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjBbNUOPhBZVCssoky2C5S3WnmiR0a492J+KU7Z6yLrwgmTfyo1ZZjEDup3DvF/GLMaaDF3QJMwY33cefMV+UzFt+xy7Usc6cI2+6mo1ZZjgy0LP/+t5RXKRCPNW69wEfWSXfb6CGrv+bklhmut0M3SqnsV3JJentRl0geZ9WC8aOzIuyHXP67fSgkGzRW6yhFKHsIoN06A5hD6gzvb64pt31Eycs/rmnNgtAmyQmUls3imdjMrbs0fM1/xNQh7qLb/mR1UT+WErgxCn/VDrDTqgC5QLvNMdp1sdf5lpYBjd+Y90NQgyj2pTNSuJZuLXFBad5lfaVAP6w6oF3nmfmFwIDAQAB
  attributes:
    tempfiledrop:
      buckets:
        - tempfiledrop
      routing-keys:
        - tempfiledrop
  whitelist:
    - /api/storagesvc/anonymous/**
    - /api/storagesvc/download/**
    - /swagger/storagesvc/api-docs
    - /tempfiledrop/**
    - /auth/user

---

###############################################################################################
# Auth Flow Configuration
###############################################################################################

spring.security.oauth2:
  client:
    registration:
      storage-gateway:
        provider: keycloak
        client-id: storage-gateway
        client-secret: a7fb42ed-4b5c-48b8-b2e5-5174dddc56df
        scope: openid,profile,email
    provider:
      keycloak: # use keycloak as registration id
        issuer-uri: http://localhost:8080/auth/realms/storage
        user-name-attribute: preferred_username
  resourceserver:
    jwt.issuer-uri: http://localhost:8080/auth/realms/storage

---

###############################################################################################
# Gateway Configuration
###############################################################################################

spring.cloud.gateway:
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders:
          - content-type
          - x-requested-with
          - Authorization
        allowedMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
          - PUT
  default-filters:
    - TokenRelay
  routes:
    ######################################## UI Endpoints
    - id: tempfiledrop
      uri: http://localhost:3000/
      predicates:
        - Path=/tempfiledrop/**
    ######################################## Swagger Routes
    - id: swaggerStorageService
      uri: http://localhost:8001/
      predicates:
        - Method=GET
        - Path=/swagger/storagesvc/api-docs
      filters:
        - RewritePath=/swagger/storagesvc(?<segment>/?.*), $\{segment}   # /swagger/storagesvc/api-docs --becomes--> /api-docs
    ####################################### Restful API Endpoints (Resource Servers)
    - id: storageService
      uri: http://localhost:8001/
      predicates:
        - Path=/api/storagesvc/**
      filters:
        - StorageAttributesInjection=true
    - id: tempfiledropWebServer
      uri: http://localhost:7001/
      predicates:
        - Path=/api/**
      filters:
        - StorageAttributesInjection=true
