###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 9090
  forward-headers-strategy: framework # https://stackoverflow.com/a/59126519/1098564 (but ours is non-servlet)

spring:
  profiles.active: dev
  application.name: apigateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG

gateway:
  whitelist:
    - /api/storagesvc/anonymous/**
    - /api/storagesvc/download/**
    - /api/storagesvc/storageinfo
    - /swagger/storagesvc/api-docs
    - /tempfiledrop/**
    - /auth/user

---

###############################################################################################
# Auth Flow Configuration
###############################################################################################

spring.security.oauth2:
  client:
    registration:
      storage-gateway:
        provider: keycloak
        client-id: storage-gateway
        client-secret: a7fb42ed-4b5c-48b8-b2e5-5174dddc56df
        scope: openid,profile,email
    provider:
      keycloak: # use keycloak as registration id
        issuer-uri: http://localhost:8080/auth/realms/storage
        user-name-attribute: preferred_username
  resourceserver:
    jwt.issuer-uri: http://localhost:8080/auth/realms/storage

---

###############################################################################################
# Gateway Configuration
###############################################################################################

spring.cloud.gateway:
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders:
          - content-type
          - x-requested-with
          - Authorization
        allowedMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
          - PUT
  default-filters:
    - TokenRelay
  routes:
    ######################################## UI Endpoints
    - id: tempfiledrop
      uri: http://localhost:3000/
      predicates:
        - Path=/tempfiledrop/**
    ######################################## Swagger Routes
    - id: swaggerStorageService
      uri: http://localhost:8001/
      predicates:
        - Method=GET
        - Path=/swagger/storagesvc/api-docs
      filters:
        - RewritePath=/swagger/storagesvc(?<segment>/?.*), $\{segment}   # /swagger/storagesvc/api-docs --becomes--> /api-docs
    ####################################### Restful API Endpoints (Resource Servers)
    - id: storageService
      uri: http://localhost:8001/
      predicates:
        - Path=/api/storagesvc/**
#      filters:
#        - RemoveRequestHeader=Cookie
    - id: tempfiledropWebServer
      uri: http://localhost:7001/
      predicates:
        - Path=/api/tempfiledrop/**
#      filters:
#        - RemoveRequestHeader=Cookie
