###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7001

spring:
  profiles:
    active: dev
  application:
    name: webserver

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring:
  data:
    mongodb:
      uri: mongodb://service_user:service_pass@localhost:27017/webDB
      authentication-database: webDB
