###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7001

spring:
  profiles.active: dev
  application.name: webserver

tempfiledrop:
  webserver:
    bucket-name: tempfiledrop
#  storagesvc-client:
#    storage-service-url: http://localhost:8001

---

###############################################################################################
# Servlet Configuration for Multipart File
###############################################################################################

#spring.servlet.multipart:
#  max-file-size: 5GB      # Max file size for each request
#  max-request-size: 5GB   # Max request size for a multipart/form-data

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb:
  uri: mongodb://service_user:service_pass@localhost:27017/webDB
  authentication-database: webDB

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:5672
    username: storage_user
    password: storage123
  cloud:
    function:
      definition: filesDownloadedChannel;filesUploadedChannel
    stream:
      rabbit.bindings:
        filesDownloadedChannel-in-0.consumer:
#          binding-routing-key-delimiter: ","
          binding-routing-key: tempfiledrop_download
        filesUploadedChannel-in-0.consumer:
#          binding-routing-key-delimiter: ","
          binding-routing-key: tempfiledrop_upload
      bindings:
        filesDownloadedChannel-in-0:
          destination: filesDownloadedExchange # mapping cloud stream output channel to rabbitmq exchange
          group: tempfiledrop                  # only 1 instance in consumer group will receive message (should be unique to your app)
        filesUploadedChannel-in-0:
          destination: filesUploadedExchange   # mapping cloud stream output channel to rabbitmq exchange
          group: tempfiledrop                  # only 1 instance in consumer group will receive message (should be unique to your app)

---
