###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7001

spring:
  profiles.active: dev
  application.name: webserver

tempfiledrop:
  bucket-name: tempfiledrop
  storage-service-url: http://localhost:8001/storagesvc

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb:
  uri: mongodb://service_user:service_pass@localhost:27017/webDB
  authentication-database: webDB

---

###############################################################################################
# Servlet Configuration for Multipart File
###############################################################################################

spring.servlet.multipart:
  max-file-size: -1      # Max file size for each request
  max-request-size: -1   # Max request size for a multipart/form-data