###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8282

spring:
  profiles.active: dev
  application.name: storage-console

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb.uri: mongodb://storage_user:storage_pass@localhost:27017/storageDB?authSource=admin

---
