###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8001

spring:
  profiles.active: dev
  application.name: storage-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: false

storagesvc:
  cors:                               # required for swagger-ui-react to call api through swagger
    enable: true
    origins: http://localhost:3000,http://localhost:3001    # use comma to add more
  anonymous-upload:
    enable: true
    max-file-size: 104857600    # 1024 * 1024 * 100 (100MB)
  storage-mode: object          # object or file
  file-storage:
    upload-directory: uploads
  object-storage:
    minio-endpoint: http://localhost:9000
    minio-access-key: minio
    minio-access-secret: minio123
  authorized-roles:
    - storage|admin
    - storage-consumer|tempfiledrop

storagelib:
  jwt-parser-keycloak:
    resource: storage-gateway           # Client
    use-resource-role-mappings: true    # use client role
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjBbNUOPhBZVCssoky2C5S3WnmiR0a492J+KU7Z6yLrwgmTfyo1ZZjEDup3DvF/GLMaaDF3QJMwY33cefMV+UzFt+xy7Usc6cI2+6mo1ZZjgy0LP/+t5RXKRCPNW69wEfWSXfb6CGrv+bklhmut0M3SqnsV3JJentRl0geZ9WC8aOzIuyHXP67fSgkGzRW6yhFKHsIoN06A5hD6gzvb64pt31Eycs/rmnNgtAmyQmUls3imdjMrbs0fM1/xNQh7qLb/mR1UT+WErgxCn/VDrDTqgC5QLvNMdp1sdf5lpYBjd+Y90NQgyj2pTNSuJZuLXFBad5lfaVAP6w6oF3nmfmFwIDAQAB

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG

---

###############################################################################################
# Servlet Configuration for Multipart File
###############################################################################################

spring.servlet.multipart:
  enabled: false          # to use apache commons fileupload instead
  max-file-size: 5GB      # Max file size for each request
  max-request-size: 5GB   # Max request size for a multipart/form-data

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb.uri: mongodb://storage_user:storage_pass@localhost:27017/storageDB?authSource=admin

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:5672
    username: storage_publisher
    password: storage123
  cloud.stream:
    rabbit.bindings:
      storageSvcChannel-out-0.producer:
        routing-key-expression: headers.routingkey    # Get Routing key from streambridge header
        declare-exchange: false                       # Disable exchange creation for access control
    bindings:
      storageSvcChannel-out-0.destination: storageSvcExchange       # mapping cloud stream output channel to rabbitmq exchange

---
