###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 8001

spring:
  profiles.active: dev
  application.name: storagesvc

storagesvc:
  expose-endpoint: http://localhost:8001
  storage-mode: object
  file-storage:
    upload-path: uploads
  object-storage:
    minio-endpoint: http://localhost:9000
    minio-access-key: minio
    minio-access-secret: minio123

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb:
  uri: mongodb://service_user:service_pass@localhost:27017/webDB
  authentication-database: webDB

---

###############################################################################################
# Servlet Configuration for Multipart File
###############################################################################################

spring.servlet.multipart:
  max-file-size: -1      # Max file size for each request
  max-request-size: -1   # Max request size for a multipart/form-data

---
