###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 8001

spring:
  profiles.active: dev
  application.name: storagesvc

springdoc.api-docs:
  path: /api-docs

tempfiledrop.storagesvc:
  expose-endpoint: http://localhost:8001
  storage-mode: object
  file-storage:
    upload-path: uploads
  object-storage:
    minio-endpoint: http://localhost:9000
    minio-access-key: minio
    minio-access-secret: minio123

---

###############################################################################################
# Servlet Configuration for Multipart File
###############################################################################################

spring.servlet.multipart:
  enabled: false
  max-file-size: 5GB      # Max file size for each request
  max-request-size: 5GB   # Max request size for a multipart/form-data

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring.data.mongodb:
  uri: mongodb://service_user:service_pass@localhost:27017/webDB
  authentication-database: webDB

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:5672
    username: storage_user
    password: storage123
  cloud.stream:
    rabbit.bindings:
      filesDownloadedChannel-out-0.producer.routing-key-expression: headers.routingkey    # Get Routing key from streambridge header
      filesUploadedChannel-out-0.producer.routing-key-expression: headers.routingkey      # Get Routing key from streambridge header
      filesDeletedChannel-out-0.producer.routing-key-expression: headers.routingkey       # Get Routing key from streambridge header
    bindings:
      filesDeletedChannel-out-0.destination: filesDeletedExchange       # mapping cloud stream output channel to rabbitmq exchange
      filesDownloadedChannel-out-0.destination: filesDownloadedExchange # mapping cloud stream output channel to rabbitmq exchange
      filesUploadedChannel-out-0.destination: filesUploadedExchange     # mapping cloud stream output channel to rabbitmq exchange

---
