###############################################################################################
# Network Configuration for Docker Compose
###############################################################################################

server.port: 8080

storagesvc:
  cors:
    origins: http://tempfiledrop-webapp
  object-storage:
    minio-endpoint: http://minio-nginx:9000

spring:
  data.mongodb.uri: mongodb://service_user:service_pass@mongodb:27017/webDB
  rabbitmq.addresses: rabbitmq:5672

keycloak:
  auth-server-url: http://keycloak:8080/auth
