version: '3.7'

services:
  mongodb:
    hostname: mongodb
    image: mongo:5.0
    container_name: 'mongo_server'
    networks:
      - proxy-net
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d # scripts will not run if /data/db is not empty
      - ./storage:/data/db # for persistent storage

networks:
  proxy-net:
    external:
      name: tempfiledrop_bridge